### ISSUE TITLE
page URL option for import

### ISSUE THREAD

**Issue by cruzanmo** [clay/claycli#36]
Readme says import takes page URI or URL `--page <uri or url> a specific page url`, but it is throwing error when using the page URL.

```
Error: Cannot parse url for site prefix!
    at getUrlPrefix (/Users/mcroney/_dev/claycli/lib/utils/urls.js:37:11)
    at Object.uriToUrl (/Users/mcroney/_dev/claycli/lib/utils/urls.js:49:17)
    at importSingleUrl (/Users/mcroney/_dev/claycli/lib/cmd/import.js:132:22)
    at Object.handler (/Users/mcroney/_dev/claycli/lib/cmd/import.js:235:12)
    at Object.self.runCommand (/Users/mcroney/_dev/claycli/node_modules/yargs/lib/command.js:233:22)
    at Object.Yargs.self._parseArgs (/Users/mcroney/_dev/claycli/node_modules/yargs/yargs.js:990:30)
    at Object.get [as argv] (/Users/mcroney/_dev/claycli/node_modules/yargs/yargs.js:927:19)
    at Object.<anonymous> (/Users/mcroney/_dev/claycli/index.js:40:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)```

**Comment by amycheng** [comment]
this *may* be fixed with this pr: https://github.com/clay/claycli/pull/37

**Comment by nelsonpecora** [comment]
https://app.zenhub.com/workspace/o/clay/claycli/issues/48
