### ISSUE TITLE
Add `y18n` to dependencies

### ISSUE THREAD

**Issue by jonwinton** [clay/claycli#75]
When running any `clay` command

```Error: Cannot find module 'y18n'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jonwinton/.nvm/versions/node/v8.9.0/lib/node_modules/claycli/node_modules/yargs/yargs.js:10:14)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)```

**Comment by nelsonpecora** [comment]
It looks like this is a dependency of yargs. Something might be borked in your install https://github.com/yargs/yargs/blob/18b2fcb19db1e652614d066098d1de4818fbcb3e/package.json#L25

**Comment by jonwinton** [comment]
You need to uninstall before re-installing.
