### ISSUE TITLE
Error thrown when current directory has no package.json

### ISSUE THREAD

**Issue by yuliyv** [clay/claycli#95]
When using claycli in a directory with no `package.json` you get the following error:

```
$ clay --version
module.js:538    throw err;
    ^

Error: Cannot find module '/CURRENT_DIR/package.json'    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)    at require (internal/module.js:11:18)
    at Object.<anonymous> (/redact/.nvm/versions/node/v8.9.0/lib/node_modules/claycli/node_modules/amphora-fs/lib/getComponents/index.js:11:9)
    at Module._compile (module.js:635:30)    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

This is likely cause by `amphora-fs` which [requires the file outside of a function call](https://github.com/clay/amphora-fs/blob/5509a196b497198410a33a23c4084935b6affec2/lib/getComponents/index.js#L11) so the fix might have to happen there.  Alternatively if no fix is possible then it should be signaled in the README that you must run claycli from a folder with a `package.json`

**Comment by nelsonpecora** [comment]
Note that this is an issue that affects _all_ `claycli` commands, not just compilation (which should also check to see if you're in the root of a clay repo, perhaps by looking for a package.json and checking if amphora is a dependency?)
